
# html lang
language: en

# 导航栏
menu:
  首页: /
  技术: /technology
  变现: /monetization
  思考: /thinking
  关于: /about

# 图标
favicon:
  small: /img/favicon-16x16.png
  medium: /img/favicon-32x32.png

# 建议页数大于1开启
paginator: true

# 头部
header:
  blank: false     # 头部链接是否新标签页打开

# 文章列表
list:
  date: true     # 文章列表是否显示日期

# 脚部
footer:
  display: true               # 是否显示footer
  context: © <a target="_blank" href="/about"> ZhangHao </a> | <a target="_blank" href="/tags"> 标签 </a> | <a target="_blank" href="/categories"> 分类 </a> | <a target="_blank" href="https://beian.miit.gov.cn/"> 陕ICP备20008129号</a> # footer内容

# 文章页
post:
  blank: false        # 文章是否新标签页打开
  backHome: true     # 文章末尾是否显示返回首页
  backHome_hr: true  # 返回首页前是否显示分割线
  backHome_prefix: "↶ "       # 返回首页的前缀内容
  backHome_content: "返回首页"  # 返回首页的主体内容
  backHome_suffix: ""          # 返回首页的后缀内容

# 标签云
tags:
  all: true       # 标签云页面是否显示全部标签

# ---------------------------------------------------------------
# Google and Baidu Analytics Config
# ---------------------------------------------------------------
# Google analytics ID
# See: https://analytics.google.com/
google_analytics: UA-166608124-1

# Baidu analytics ID
# See: https://tongji.baidu.com/
baidu_analytics: 0c64a5657309290fd8f5efe33fcbcdb4

# ---------------------------------------------------------------
# Google AdSense Config
# ---------------------------------------------------------------
# Google AdSense
google_adsense:
  enable: true
  client: ca-pub-4128258433761966
  js_src: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js

# ---------------------------------------------------------------
# Math and Chart config
# ---------------------------------------------------------------
math:
  enable: true
  # If true, this function will be enabled on every page.
  # If false, this function will be enabled only if the page where `math: true` is set in `Front-matter`.
  per_page: true
  # Optional values: mathjax | katex
  engine: katex
  mathjax:
    cdn: https://cdn.jsdelivr.net/npm/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    # See: https://mhchem.github.io/MathJax-mhchem/
    mhchem:
      enable: false
      mhchem_js: https://cdn.jsdelivr.net/npm/mathjax-mhchem@3.3.2/mhchem.min.js
  katex:
    cdn: https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.css
    # See: https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex
    copy_tex:
      enable: true
      copy_tex_js: https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/contrib/copy-tex.min.js
      copy_tex_css: https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/contrib/copy-tex.css

copyright:
  enable: true
  license: All articles in this blog are licensed under <a rel="license" href="https://creativecommons.org/licenses/by-nc-nd/3.0">CC BY-NC-SA 3.0</a> unless stating additionally.
